import React, { useState } from 'react';
import { Icons } from '../components/ui/Icons';
import { useRestaurant } from '../context/RestaurantContext';
import { analyzeMenuImage } from '../services/geminiService';
import { MenuItem } from '../types';

export const Onboarding: React.FC = () => {
    const { setViewMode, updateRestaurantProfile, replaceMenu, user } = useRestaurant();
    const [step, setStep] = useState(1);
    const [loading, setLoading] = useState(false);
    const [scanning, setScanning] = useState(false);

    // Form Data
    const [formData, setFormData] = useState({
        name: '',
        type: '',
        location: '',
        phone: ''
    });

    // Menu Scanning Data
    const [menuImage, setMenuImage] = useState<string | null>(null);
    const [scannedItems, setScannedItems] = useState<Partial<MenuItem>[]>([]);

    // Default placeholder image if none provided
    const DEFAULT_FOOD_IMG = "https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=2670&auto=format&fit=crop";

    const handleNext = () => {
        if (step < 5) {
            setStep(step + 1);
        } else {
            finishOnboarding();
        }
    };

    const finishOnboarding = async () => {
        setLoading(true);

        try {
            // 1. Create the restaurant profile and GET THE NEW ID
            const newProfile = await updateRestaurantProfile({
                name: formData.name,
                type: formData.type || 'Fine Dining',
                location: formData.location,
                phone: formData.phone,
                email: user?.email // Pass user email to link for recovery 
            });

            const newRestaurantId = newProfile.id;

            // 2. Commit the menu items using the NEW ID
            if (scannedItems.length > 0) {
                const finalMenu: MenuItem[] = scannedItems.map((item, index) => ({
                    id: `ignore-db-will-generate`, // ID is generated by Supabase
                    restaurantId: newRestaurantId, // CRITICAL FIX: Use actual ID
                    name: item.name || 'Unknown Dish',
                    description: item.description || '',
                    price: item.price || 0,
                    category: item.category as any || 'main',
                    image: item.image || DEFAULT_FOOD_IMG,
                    dietary: item.dietary || [],
                    inStock: true,
                    isPopular: index < 3
                }));

                // Re-using replaceMenu but it's really an initial insert
                // We need to ensure replaceMenu in context uses the restaurantId passed in items, or currentRestaurant
                // Since updateRestaurantProfile sets currentRestaurant, it should work, but timing matters.
                await replaceMenu(finalMenu);
            }

            // 3. Redirect to App with correct URL parameter
            // We need to reload or update URL to include ?rid=...
            const newUrl = `${window.location.pathname}?rid=${newRestaurantId}`;
            window.history.pushState({ path: newUrl }, '', newUrl);

            setTimeout(() => {
                setViewMode('APP');
                setLoading(false);
            }, 1000);

        } catch (err) {
            console.error("Onboarding failed:", err);
            const errorMessage = err instanceof Error ? err.message : "Unknown error";
            alert(`Failed to create restaurant: ${errorMessage}`);
            setLoading(false);
        }
    };

    const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        // Convert to base64
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = async () => {
            const base64 = reader.result as string;
            setMenuImage(base64);
            setScanning(true);

            // Remove data URL prefix for API
            const base64Data = base64.split(',')[1];
            const items = await analyzeMenuImage(base64Data);

            setScannedItems(items.map(i => ({ ...i, image: DEFAULT_FOOD_IMG })));
            setScanning(false);
            setStep(4); // Move to review step
        };
    };

    const handleDishImageUpload = (index: number, e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => {
            const newItems = [...scannedItems];
            newItems[index] = { ...newItems[index], image: reader.result as string };
            setScannedItems(newItems);
        };
    };

    const updateScannedItem = (index: number, field: keyof MenuItem, value: any) => {
        const newItems = [...scannedItems];
        newItems[index] = { ...newItems[index], [field]: value };
        setScannedItems(newItems);
    };

    if (loading) {
        return (
            <div className="min-h-screen bg-stone-900 flex flex-col items-center justify-center text-center p-6">
                <div className="w-24 h-24 border-4 border-stone-800 border-t-gold-500 rounded-full animate-spin mb-8"></div>
                <h2 className="text-3xl font-display text-white mb-2">Setting up {formData.name}</h2>
                <div className="space-y-2">
                    <p className="text-gold-400 text-sm uppercase tracking-widest animate-pulse">Setting up Digital Kitchen...</p>
                    <p className="text-stone-500 text-xs uppercase tracking-widest delay-100">Digitizing Menu Items...</p>
                    <p className="text-stone-500 text-xs uppercase tracking-widest delay-200">Polishing Silverware...</p>
                </div>
            </div>
        );
    }

    // ... (Steps 1-4 UI remains identical, keeping concise for update) ...
    // Returning the full UI structure to ensure file validity
    return (
        <div className="min-h-screen bg-white flex flex-col md:flex-row">
            <div className="hidden md:flex w-1/3 bg-stone-900 relative overflow-hidden items-center justify-center p-12 text-center">
                <div className="absolute inset-0 opacity-20">
                    <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_#D4AF37_1px,_transparent_1px)] bg-[length:24px_24px]"></div>
                </div>
                <div className="relative z-10">
                    <div className="w-20 h-20 border-2 border-gold-500 rounded-sm flex items-center justify-center rotate-45 mx-auto mb-8">
                        <div className="-rotate-45 font-display font-bold text-4xl text-white">R</div>
                    </div>
                    <h2 className="font-display text-3xl text-white mb-4">RestroFi</h2>
                    <p className="font-serif italic text-stone-400">"The beginning of a legacy."</p>

                    {step === 4 && (
                        <div className="mt-12 p-6 bg-stone-800/50 rounded-xl border border-stone-700 backdrop-blur-sm animate-fade-in-up">
                            <Icons.Check className="w-8 h-8 text-green-500 mx-auto mb-2" />
                            <p className="text-white font-bold">{scannedItems.length} Items Detected</p>
                            <p className="text-xs text-stone-400 mt-1">AI has successfully read your menu card.</p>
                        </div>
                    )}
                </div>
            </div>

            <div className="flex-1 flex flex-col h-screen overflow-hidden">
                <div className="p-8 flex justify-between items-center bg-white z-10 border-b border-stone-50">
                    <button onClick={() => setViewMode('LANDING')} className="text-stone-400 hover:text-stone-900 flex items-center gap-2 text-sm font-bold uppercase tracking-widest">
                        <Icons.Left className="w-4 h-4" /> Back
                    </button>
                    <div className="text-xs font-bold text-stone-300 uppercase tracking-widest">Step {step} of 5</div>
                </div>

                <div className="flex-1 overflow-y-auto custom-scrollbar">
                    <div className="flex flex-col items-center justify-start min-h-full p-6 md:p-12">
                        <div className="max-w-xl w-full animate-fade-in-up pb-20">
                            <div className="flex gap-2 mb-10">
                                {[1, 2, 3, 4, 5].map(i => (
                                    <div key={i} className={`h-1 flex-1 rounded-full transition-colors duration-500 ${i <= step ? 'bg-gold-500' : 'bg-stone-100'}`}></div>
                                ))}
                            </div>

                            {step === 1 && (
                                <div className="space-y-6">
                                    <div>
                                        <h1 className="font-display text-4xl font-bold text-stone-900 mb-2">Name your venue</h1>
                                        <p className="text-stone-500">What is the name of your establishment?</p>
                                    </div>
                                    <div>
                                        <label className="block text-xs font-bold uppercase tracking-widest text-stone-400 mb-2">Restaurant Name</label>
                                        <input
                                            autoFocus
                                            type="text"
                                            className="w-full text-2xl font-display font-bold border-b-2 border-stone-200 py-2 focus:border-gold-500 focus:outline-none bg-transparent placeholder-stone-300 transition-colors"
                                            placeholder="e.g. The Royal Oak"
                                            value={formData.name}
                                            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs font-bold uppercase tracking-widest text-stone-400 mb-2">Cuisine / Type</label>
                                        <select
                                            className="w-full text-lg border-b-2 border-stone-200 py-2 focus:border-gold-500 focus:outline-none bg-transparent transition-colors"
                                            value={formData.type}
                                            onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                                        >
                                            <option value="" disabled>Select Type</option>
                                            <option value="Fine Dining">Fine Dining</option>
                                            <option value="Bistro">Bistro</option>
                                            <option value="Cafe">Cafe</option>
                                            <option value="Lounge">Lounge</option>
                                            <option value="Patisserie">Patisserie</option>
                                        </select>
                                    </div>
                                </div>
                            )}

                            {step === 2 && (
                                <div className="space-y-6">
                                    <div>
                                        <h1 className="font-display text-4xl font-bold text-stone-900 mb-2">Where are you?</h1>
                                        <p className="text-stone-500">Help guests find your location.</p>
                                    </div>
                                    <div>
                                        <label className="block text-xs font-bold uppercase tracking-widest text-stone-400 mb-2">City & Address</label>
                                        <input
                                            autoFocus
                                            type="text"
                                            className="w-full text-xl border-b-2 border-stone-200 py-2 focus:border-gold-500 focus:outline-none bg-transparent placeholder-stone-300 transition-colors"
                                            placeholder="e.g. New Delhi, Connaught Place"
                                            value={formData.location}
                                            onChange={(e) => setFormData({ ...formData, location: e.target.value })}
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs font-bold uppercase tracking-widest text-stone-400 mb-2">Contact Phone (Optional)</label>
                                        <input
                                            type="tel"
                                            className="w-full text-xl border-b-2 border-stone-200 py-2 focus:border-gold-500 focus:outline-none bg-transparent placeholder-stone-300 transition-colors"
                                            placeholder="+91..."
                                            value={formData.phone}
                                            onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                                        />
                                    </div>
                                </div>
                            )}

                            {step === 3 && (
                                <div className="space-y-6">
                                    <div>
                                        <h1 className="font-display text-4xl font-bold text-stone-900 mb-2">Digitize Your Menu</h1>
                                        <p className="text-stone-500">Upload a photo of your menu card. Our AI will extract dishes, prices, and descriptions in seconds.</p>
                                    </div>

                                    <div className="mt-8 border-2 border-dashed border-stone-300 rounded-2xl p-12 text-center hover:bg-stone-50 hover:border-gold-400 transition-all group relative cursor-pointer">
                                        <input
                                            type="file"
                                            accept="image/*"
                                            onChange={handleImageUpload}
                                            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
                                        />
                                        {scanning ? (
                                            <div className="flex flex-col items-center">
                                                <div className="w-12 h-12 border-4 border-gold-200 border-t-gold-600 rounded-full animate-spin mb-4"></div>
                                                <p className="font-bold text-stone-900">Analyzing Menu...</p>
                                                <p className="text-xs text-stone-500 mt-2">Identifying dishes & prices</p>
                                            </div>
                                        ) : (
                                            <>
                                                <div className="w-16 h-16 bg-stone-100 text-stone-400 rounded-full flex items-center justify-center mx-auto mb-4 group-hover:bg-gold-100 group-hover:text-gold-600 transition-colors">
                                                    <Icons.Image className="w-8 h-8" />
                                                </div>
                                                <h3 className="text-lg font-bold text-stone-700 group-hover:text-gold-700">Click to Upload Menu Card</h3>
                                                <p className="text-sm text-stone-400 mt-2">Supports JPG, PNG (Max 5MB)</p>
                                            </>
                                        )}
                                    </div>
                                    <div className="text-center">
                                        <button onClick={() => setStep(4)} className="text-sm text-stone-400 underline hover:text-stone-600">
                                            Skip this step (Add manually later)
                                        </button>
                                    </div>
                                </div>
                            )}

                            {step === 4 && (
                                <div className="space-y-6">
                                    <div>
                                        <h1 className="font-display text-3xl font-bold text-stone-900 mb-2">Review & Customize</h1>
                                        <p className="text-stone-500">We found {scannedItems.length} items. Verify prices and upload dish photos.</p>
                                    </div>

                                    <div className="space-y-4">
                                        {scannedItems.length === 0 ? (
                                            <div className="text-center py-10 border border-stone-100 rounded-xl bg-stone-50">
                                                <p className="text-stone-400">No items found. You can add them later in Admin dashboard.</p>
                                            </div>
                                        ) : (
                                            scannedItems.map((item, idx) => (
                                                <div key={idx} className="bg-white border border-stone-200 rounded-xl p-4 flex flex-col md:flex-row gap-4 shadow-sm hover:border-gold-300 transition-colors">
                                                    <div className="relative w-full md:w-24 h-24 bg-stone-100 rounded-lg overflow-hidden shrink-0 group">
                                                        <img src={item.image || DEFAULT_FOOD_IMG} alt={item.name} className="w-full h-full object-cover" />
                                                        <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                                                            <Icons.Image className="w-6 h-6 text-white" />
                                                            <input
                                                                type="file"
                                                                accept="image/*"
                                                                onChange={(e) => handleDishImageUpload(idx, e)}
                                                                className="absolute inset-0 cursor-pointer opacity-0"
                                                            />
                                                        </div>
                                                    </div>

                                                    <div className="flex-1 space-y-3">
                                                        <div className="flex gap-4">
                                                            <input
                                                                type="text"
                                                                value={item.name}
                                                                onChange={(e) => updateScannedItem(idx, 'name', e.target.value)}
                                                                className="flex-1 font-bold text-stone-900 border-b border-stone-200 focus:border-gold-500 outline-none pb-1 bg-transparent"
                                                                placeholder="Dish Name"
                                                            />
                                                            <div className="flex items-center w-24">
                                                                <span className="text-stone-400 text-sm mr-1">₹</span>
                                                                <input
                                                                    type="number"
                                                                    value={item.price}
                                                                    onChange={(e) => updateScannedItem(idx, 'price', Number(e.target.value))}
                                                                    className="w-full font-bold text-stone-900 border-b border-stone-200 focus:border-gold-500 outline-none pb-1 bg-transparent"
                                                                />
                                                            </div>
                                                        </div>
                                                        <input
                                                            type="text"
                                                            value={item.description}
                                                            onChange={(e) => updateScannedItem(idx, 'description', e.target.value)}
                                                            className="w-full text-sm text-stone-500 border-b border-stone-100 focus:border-gold-300 outline-none pb-1 bg-transparent"
                                                            placeholder="Description"
                                                        />
                                                        <div className="flex gap-2">
                                                            {['V', 'VG', 'GF', 'JAIN'].map(tag => (
                                                                <button
                                                                    key={tag}
                                                                    onClick={() => {
                                                                        const tags = item.dietary || [];
                                                                        const newTags = tags.includes(tag) ? tags.filter(t => t !== tag) : [...tags, tag];
                                                                        updateScannedItem(idx, 'dietary', newTags);
                                                                    }}
                                                                    className={`text-[10px] border px-2 py-0.5 rounded transition-colors ${item.dietary?.includes(tag) ? 'bg-stone-800 text-gold-400 border-stone-800' : 'text-stone-400 border-stone-200'}`}
                                                                >
                                                                    {tag}
                                                                </button>
                                                            ))}
                                                        </div>
                                                    </div>
                                                </div>
                                            ))
                                        )}
                                    </div>
                                </div>
                            )}

                            {step === 5 && (
                                <div className="space-y-6 text-center">
                                    <div className="w-20 h-20 bg-gold-100 rounded-full flex items-center justify-center mx-auto text-gold-600 mb-4">
                                        <Icons.Check className="w-8 h-8" />
                                    </div>
                                    <div>
                                        <h1 className="font-display text-4xl font-bold text-stone-900 mb-2">Ready to Launch?</h1>
                                        <p className="text-stone-500">Review your details before going live.</p>
                                    </div>

                                    <div className="bg-stone-50 p-6 rounded-xl text-left border border-stone-100 shadow-sm">
                                        <div className="mb-4">
                                            <p className="text-[10px] uppercase tracking-widest text-stone-400 font-bold">Name</p>
                                            <p className="font-display text-xl font-bold text-stone-900">{formData.name}</p>
                                        </div>
                                        <div className="mb-4">
                                            <p className="text-[10px] uppercase tracking-widest text-stone-400 font-bold">Type</p>
                                            <p className="font-serif text-stone-700">{formData.type}</p>
                                        </div>
                                        <div>
                                            <p className="text-[10px] uppercase tracking-widest text-stone-400 font-bold">Location</p>
                                            <p className="font-serif text-stone-700">{formData.location}</p>
                                        </div>
                                        {formData.phone && (
                                            <div className="mt-4 pt-4 border-t border-stone-200">
                                                <p className="text-[10px] uppercase tracking-widest text-stone-400 font-bold">Contact</p>
                                                <p className="font-serif text-stone-700">{formData.phone}</p>
                                            </div>
                                        )}
                                        <div className="mt-4 pt-4 border-t border-stone-200">
                                            <p className="text-[10px] uppercase tracking-widest text-stone-400 font-bold">Menu</p>
                                            <p className="font-serif text-stone-700">{scannedItems.length} items ready to serve</p>
                                        </div>
                                    </div>
                                </div>
                            )}

                            <div className="mt-10 flex gap-4">
                                {step > 1 && (
                                    <button
                                        onClick={() => setStep(step - 1)}
                                        className="px-6 py-4 rounded-full font-bold text-stone-500 hover:bg-stone-100 transition-colors"
                                    >
                                        Back
                                    </button>
                                )}
                                <button
                                    onClick={handleNext}
                                    disabled={(step === 1 && !formData.name)}
                                    className="flex-1 bg-stone-900 text-gold-400 py-5 rounded-full font-bold tracking-widest uppercase hover:bg-black hover:text-gold-300 transition-all shadow-lg hover:shadow-gold-500/20 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-3"
                                >
                                    {step === 5 ? 'Launch Restaurant' : 'Continue'} <Icons.Right className="w-4 h-4" />
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="p-4 text-center md:text-right bg-white relative z-20">
                    <p className="text-[10px] uppercase tracking-[0.2em] text-stone-300 font-bold">Powered by RestroFi</p>
                </div>
            </div>
        </div>
    );
};
